apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "k8s-secret-creator.fullname" . }}"
  labels:
    {{- include "k8s-secret-creator.labels" . | nindent 4 }}

data:
  K8S_NAMESPACE: "{{ .Release.Namespace | default "" }}"
  SECRET_PREFIX: "{{ .Values.conf.secret_prefix | default "ksc-" }}"
