apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "k8s-secret-creator.fullname" . }}"
  labels:
    {{- include "k8s-secret-creator.labels" . | nindent 4 }}

data:
  API_TOKEN: "{{ .Values.auth.api_token | default "" | b64enc }}"
