{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-secret-creator.serviceAccountName" . }}
  labels:
    {{- include "k8s-secret-creator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-secret-creator.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-secret-creator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-secret-creator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "k8s-secret-creator.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
