name: Build docker

on:
  workflow_call:
    inputs:
      oci_tag:
        description: 'Docker image tag'
        type: string
        required: true
      version:
        description: 'Docker image version'
        type: string
        required: true
      push:
        description: 'Push to the image registry'
        type: boolean
        required: true

jobs:
  build:
    name: Build ${{ inputs.oci_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ inputs.oci_tag }}:${{ inputs.version }},${{ inputs.oci_tag }}:latest
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
