name: CI pipeline

on:
  release:
    types: [published]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  configure-workflow:
    name: Configure workflow
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        name: Configure skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["workflow_dispatch", "schedule", "release"]'

  test:
    uses: ./.github/workflows/test.yaml
    needs: [configure-workflow]
    if: needs.configure-workflow.outputs.should_skip != 'true'

  build-docker:
    uses: ./.github/workflows/build-docker.yaml
    needs: [test]
    with:
      oci_tag: ghcr.io/qcdis/k8s-secret-creator
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}

  build-helm:
    uses: ./.github/workflows/build-helm.yaml
    needs: [test]
    with:
      oci_repo: ghcr.io/qcdis/charts
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}
