name: Test

on:
  workflow_call:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          path: ${{ env.CONDA }}/envs
          environment-file: environment.yaml
          activate-environment: jupyterlab
          use-mamba: true

      - name: Install requirements
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-environment-${{ runner.os }}-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            conda-environment-${{ runner.os }}-
        id: cache-conda

      - name: Pytest
        shell: bash -l {0}
        run: |
          minikube start
          pytest
