name: Test

on:
  workflow_call:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Pytest
        run: |
          minikube start
          pytest
